name: After dispatch

on:
  workflow_run:
    workflows:
      - On dispatch
    types:
      - completed

jobs:
  something:
    if: github.event.workflow_run.conclusion == 'success'
    name: After dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          echo "OK!"
          echo "{{ fromJSON(github.event) }}"
