name: On dispatch

on:
  repository_dispatch:
    types: [content-build]

jobs:
  something:
    name: Do something
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: |
          echo "${{ fromJSON(github.event )}}"
