name: On dispatch

on:
  repository_dispatch:
    types: [content-build]

permissions:
  actions: write

jobs:
  something:
    name: Do something
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: |
          echo "${{ toJSON(github.event )}}"
      - name: Trigger Another Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: 'jonime',
              repo: 'test-gh-actions',
              workflow_id: 'separate.yml',
              ref: 'main',
              inputs: {
                test: 'something'
              }
            });
            console.log(response);
