name: Separate workflow

on:
  workflow_dispatch:
    inputs:
      test:
        required: true
        type: string

jobs:
  something:
    name: Something
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "${{ toJson(github.event.client_payload) }}"
