name: Test things

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "koira=kissa" >> $GITHUB_ENV
      - run: |
          echo "${{ toJson(env) }}"
      - run: |
          env
